server:
  port: 9001
  address: 127.0.0.1
# ?????????
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  # Redis?????
  data:
    redis:
      host: localhost
      port: 6379
#  password: 1234

# mybatis???
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml

#配置拦截器放行路径
#interception:
#  release:
#    Urls:
#      - /admin/system/index/login
#      - /admin/system/index/generateCode
#      - /doc.html
